name: boxofbooks
favicon: null
layout_spectrum: 0.49234
typography_spectrum: 0.34547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47b6fe'
    - '#ef6500'
    - '#f8f9fb'
    - '#342b1f'
    - '#41ff7b'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
