name: boxofbooks
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47b6fe'
    - '#ef6500'
    - '#f8f9fb'
    - '#342b1f'
    - '#41ff7b'
  brandStrength: 0.9592826927546412
  lightness: 0.9507705848664045
  saturation: 0
  rhythmicContrast: 0.3681128094904125
purpose: []
